name: msw-server
on:
  push:
    branches:
      - "main"
      - "alpha"
  pull_request:

jobs:
  test:
    name: "node ${{ matrix.node }} ${{matrix.browser}}  ${{ matrix.os }} "
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14, 12, 10]
        browser: ["chrome:headless", "firefox:headless"]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v1
      - run: yarn --frozen-lockfile
      - run: NEXT_PUBLIC_IS_TESTCAFE=1 xvfb-run --server-args="-screen 0 1280x720x24" node ./runtestCafe.js
#       - run: yarn test
#       - name: Run TestCafe Tests
#         uses: benmonro/testcafe-action@benv1
#         with:
#           cmd: "node runtestCafe.js"
#           args: "${{ matrix.browser}}"
  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/checkout@v1
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: ls -asl dist
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
